import dotenv from "dotenv";

dotenv.config();

export const configs = {
  APP_PORT: Number(process.env.APP_PORT),
  APP_HOST: process.env.APP_HOST,
  MONGO_URL: process.env.MONGO_URL,

  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,

  SMPT_EMAIL: process.env.SMPT_EMAIL,
  SMPT_PASSWORD: process.env.SMPT_PASSWORD,
  FRONTEND_URL: process.env.FRONTEND_URL,

  JWS_ACTION_FORGOT_PASSWORD_SECRET:
    process.env.JWS_ACTION_FORGOT_PASSWORD_SECRET,
  JWS_ACTION_FORGOT_PASSWORD_EXPIRES_IN:
    process.env.JWS_ACTION_FORGOT_PASSWORD_EXPIRES_IN,

  JWS_ACTION_VERIFY_EMAIL_SECRET: process.env.JWS_ACTION_VERIFY_EMAIL_SECRET,
  JWS_ACTION_VERIFY_EMAIL_EXPIRES_IN:
    process.env.JWS_ACTION_VERIFY_EMAIL_EXPIRES_IN,
};
